# Generated by Django 6.1 on 2026-08-24 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_doctor_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دارو')),
                ('unit', models.CharField(max_length=100, verbose_name='واحد')),
                ('dosage', models.CharField(default='', max_length=200, verbose_name='دوز مصرفی')),
                ('current_inventory', models.IntegerField(default=0, verbose_name='موجودی فعلی')),
                ('refill_reminder_threshold', models.IntegerField(blank=True, null=True, verbose_name='آستانه اطلاع\u200cرسانی تجدید موجودی')),
                ('refill_reminder_sent', models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی تجدید ارسال شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('daily', 'روزانه'), ('specific_days', 'روزهای خاص'), ('every_n_days', 'هر N روز'), ('every_x_hours', 'هر X ساعت')], max_length=20, verbose_name='نوع تکرار')),
                ('specific_days', models.JSONField(blank=True, default=list, verbose_name='روزهای خاص')),
                ('n_days_interval', models.IntegerField(blank=True, null=True, verbose_name='فاصله روزها (N)')),
                ('x_hours_interval', models.IntegerField(blank=True, null=True, verbose_name='فاصله ساعت (X)')),
                ('medication_times', models.JSONField(blank=True, default=list, verbose_name='ساعت\u200cهای مصرف')),
                ('anchor_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایه')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication', verbose_name='دارو')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی دارو',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای دارو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='زمان برنامه\u200cریزی شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('taken', 'مصرف شده'), ('skipped', 'رد شده'), ('missed', 'از دست رفته')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شده')),
                ('token', models.CharField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='توکن یک\u200cبار مصرف')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='medications.medication', verbose_name='دارو')),
            ],
            options={
                'verbose_name': 'مصرف دارو',
                'verbose_name_plural': 'مصرف داروها',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_time', 'status'], name='medications_schedul_d2bc77_idx'), models.Index(fields=['medication', 'scheduled_time'], name='medications_medicat_faff08_idx')],
            },
        ),
    ]
