# Generated by Django 6.1 on 2026-08-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_ids', models.JSONField(verbose_name='شناسه\u200cهای مصرف')),
                ('error_message', models.TextField(verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medication', verbose_name='دارو')),
            ],
            options={
                'verbose_name': 'لاگ خطای ایمیل',
                'verbose_name_plural': 'لاگ\u200cهای خطای ایمیل',
                'ordering': ['-created_at'],
            },
        ),
    ]
