# Generated by Django 6.0.7 on 2026-08-25 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_unit_choices'),
        ('medications', '0002_emailfailurelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailfailurelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'email failure log', 'verbose_name_plural': 'email failure logs'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-created_at'], 'verbose_name': 'medication', 'verbose_name_plural': 'medications'},
        ),
        migrations.AlterModelOptions(
            name='medicationintake',
            options={'ordering': ['scheduled_time'], 'verbose_name': 'medication intake', 'verbose_name_plural': 'medication intakes'},
        ),
        migrations.AlterModelOptions(
            name='medicationschedule',
            options={'ordering': ['-created_at'], 'verbose_name': 'medication schedule', 'verbose_name_plural': 'medication schedules'},
        ),
        migrations.AlterField(
            model_name='emailfailurelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='emailfailurelog',
            name='error_message',
            field=models.TextField(verbose_name='error message'),
        ),
        migrations.AlterField(
            model_name='emailfailurelog',
            name='intake_ids',
            field=models.JSONField(verbose_name='intake IDs'),
        ),
        migrations.AlterField(
            model_name='emailfailurelog',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medication', verbose_name='medication'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='current_inventory',
            field=models.IntegerField(default=0, verbose_name='current inventory'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='', max_length=200, verbose_name='dosage'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=200, verbose_name='medication name'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='refill_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='refill reminder sent'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='refill_reminder_threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='refill reminder threshold'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('pill', 'Pill'), ('sachet', 'Sachet'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('tube', 'Tube'), ('drop', 'Drop'), ('spray', 'Spray'), ('patch', 'Patch'), ('suppository', 'Suppository'), ('dose', 'Dose'), ('ml', 'mL'), ('mg', 'mg'), ('g', 'g'), ('mcg', 'mcg'), ('unit', 'Unit')], max_length=100, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='medications.medication', verbose_name='medication'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recorded at'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='reminder sent'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='scheduled_time',
            field=models.DateTimeField(verbose_name='scheduled time'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='one-time token'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='anchor_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anchor datetime'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('specific_days', 'Specific Days'), ('every_n_days', 'Every N Days'), ('every_x_hours', 'Every X Hours')], max_length=20, verbose_name='frequency type'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication', verbose_name='medication'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='medication_times',
            field=models.JSONField(blank=True, default=list, verbose_name='medication times'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='n_days_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='day interval (N)'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='specific_days',
            field=models.JSONField(blank=True, default=list, verbose_name='specific days'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='x_hours_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='hour interval (X)'),
        ),
    ]
