# Generated by Django 6.1 on 2026-08-28 06:28

from django.db import migrations, models


def missed_to_pending(apps, schema_editor):
    MedicationIntake = apps.get_model("medications", "MedicationIntake")
    MedicationIntake.objects.filter(status="missed").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_add_unit_choices'),
    ]

    operations = [
        migrations.RunPython(missed_to_pending, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='medicationintake',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('skipped', 'Skipped')], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
