# Generated by Django 6.0.7 on 2026-09-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_telegram_chat_id_patient_telegram_username'),
        ('medications', '0004_remove_missed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='activation code')),
                ('telegram_chat_id', models.CharField(max_length=64, verbose_name='Telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('used_by_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_activation_codes', to='accounts.patient', verbose_name='used by patient')),
            ],
            options={
                'verbose_name': 'Telegram activation code',
                'verbose_name_plural': 'Telegram activation codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_chat_id'], name='medications_telegra_0cc7ab_idx'), models.Index(fields=['expires_at'], name='medications_expires_20547d_idx')],
            },
        ),
    ]
