# Generated by Django 6.1 on 2026-09-17 07:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_medication_current_inventory_non_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='current_inventory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='current inventory'),
        ),
    ]
