# Generated by Django 6.1 on 2026-09-17 07:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_medication_current_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='current_inventory',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='current inventory'),
        ),
    ]
