# Generated by Django 6.1 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_unit_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telegram_chat_id',
            field=models.CharField(
                blank=True,
                help_text='Telegram chat ID if the patient has linked their account.',
                max_length=64,
                null=True,
                unique=True,
                verbose_name='Telegram chat ID',
            ),
        ),
        migrations.AddField(
            model_name='patient',
            name='telegram_username',
            field=models.CharField(
                blank=True,
                help_text='Display username from Telegram, if available.',
                max_length=64,
                null=True,
                verbose_name='Telegram username',
            ),
        ),
    ]
