# Generated by Django 6.1 on 2026-08-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_doctor_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ (میلادی)')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_booked', models.BooleanField(default=False, verbose_name='رزرو شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='accounts.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='active', max_length=10, verbose_name='وضعیت')),
                ('doctor_summary', models.TextField(blank=True, default='', verbose_name='خلاصه ویزیت پزشک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patient', verbose_name='بیمار')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.timeslot', verbose_name='نوبت')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-time_slot__date', '-time_slot__start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time'), name='unique_doctor_date_start_time'),
        ),
    ]
