# Generated by Django 6.1 on 2026-08-22 19:07

import django.db.models.deletion
import medical_tests.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='دسته\u200cبندی')),
                ('pdf_file', models.FileField(upload_to=medical_tests.models.medical_test_pdf_upload_to, verbose_name='فایل PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نتیجه آزمایش',
                'verbose_name_plural': 'نتیجه آزمایش\u200cها',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
