# Generated by Django 6.1 on 2026-08-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltestresult',
            name='category',
            field=models.CharField(choices=[('blood', 'آزمایش خون'), ('urine', 'آزمایش ادرار'), ('stool', 'آزمایش مدفوع'), ('thyroid', 'آزمایش تیروئید'), ('glucose', 'آزمایش قند خون'), ('lipid', 'آزمایش چربی خون'), ('hormone', 'آزمایش هورمونی'), ('liver', 'آزمایش کبد'), ('kidney', 'آزمایش کلیه'), ('vitamin', 'آزمایش ویتامین\u200cها و مواد معدنی')], max_length=20, verbose_name='نوع آزمایش'),
        ),
    ]
