# Generated by Django 6.1 on 2026-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tests', '0002_alter_medicaltestresult_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltestresult',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام آزمایش'),
        ),
    ]
